### ISSUE TITLE
小白请教个小问题

### ISSUE THREAD

**Issue by LittleWhiteofCode01** [CoinkWang/Y2BDoubleSubs#2]
你好，我是个编程小白，请问怎么能让英文显示在中文下面呢？
例如：苹果/apple       而不是：apple/苹果
                                      
我有实现这个的需要，谢谢指点。不要笑话我。

**Comment by CoinkWang** [comment]
可以将修改第39行和54行：

39:
`localeJson.events[i].segs[0].utf8 += ('\n' + defaultJson.events[i].segs[0].utf8) // defaultJson.events[i].segs[0].utf8 += ('\n' + localeJson.events[i].segs[0].utf8)`

54:
`localeJson.events[i].segs[0].utf8 = localeJson.events[i].segs[0].utf8 + '\n' + line // localeJson.events[i].segs[0].utf8 = line + '\n' +  localeJson.events[i].segs[0].utf8`

把前后顺序调换一下即可，完整如下：
[hook_request.txt](https://github.com/CoinkWang/Y2BDoubleSubs/files/4638666/hook_request.txt)

大家都是从小白过来的，不会笑话的哈，加油～

**Comment by LittleWhiteofCode01** [comment]
> 可以将修改第39行和54行：
> 
> 39:
> `localeJson.events[i].segs[0].utf8 += ('\n' + defaultJson.events[i].segs[0].utf8) // defaultJson.events[i].segs[0].utf8 += ('\n' + localeJson.events[i].segs[0].utf8)`
> 
> 54:
> `localeJson.events[i].segs[0].utf8 = localeJson.events[i].segs[0].utf8 + '\n' + line // localeJson.events[i].segs[0].utf8 = line + '\n' + localeJson.events[i].segs[0].utf8`
> 
> 把前后顺序调换一下即可，完整如下：
> [hook_request.txt](https://github.com/CoinkWang/Y2BDoubleSubs/files/4638666/hook_request.txt)
> 
> 大家都是从小白过来的，不会笑话的哈，加油～

感谢
