### ISSUE TITLE
不能够自动开启双字幕

### ISSUE THREAD

**Issue by EvanLo666** [CoinkWang/Y2BDoubleSubs#4]
youtube设置里我是设置了播放视频自动加载字幕，但是开启该脚本后就不能够自动加载双字幕了

**Comment by CoinkWang** [comment]
脚本加载需要一点时间，自动开启的脚本可能先于我的脚本执行了。你可以尝试重新打开字幕。

**Comment by CoinkWang** [comment]
目前没有想到解决方案，油猴脚本有很多，我做不到兼容全部的其它插件。
