### ISSUE TITLE
自动生成英文字幕的视频启用后不显示字幕

### ISSUE THREAD

**Issue by led-ury** [CoinkWang/Y2BDoubleSubs#7]
仅英文都无法开启，解说词框也打不开

**Comment by CoinkWang** [comment]
解说词方法仅供参考，请使用我发布在 Greasy Fork 上的脚本。

**Comment by led-ury** [comment]
> 解说词方法仅供参考，请使用我发布在 Greasy Fork 上的脚本。

使用的是Greasy Fork 上的版本，在视频英文字幕为自动生成的情况下不显示字幕，不论是英文还是翻译后的。
