### ISSUE TITLE
字幕能否优先选择原视频使用的语言进行翻译

### ISSUE THREAD

**Issue by ClTheDove** [CoinkWang/Y2BDoubleSubs#9]
明明在看日语视频但是却选用英文字幕进行翻译.......
Egg Pain

**Comment by ClTheDove** [comment]
有的时候已经都有中文（翻译）字幕了，但是还是会选择英文字幕进行翻译..........

**Comment by ClTheDove** [comment]
有的时候都已经有中文（翻译）字幕了，但还是会选择英文字幕进行翻译..........

**Comment by CoinkWang** [comment]
你好，我现在上班了，好累... 我不想改了，辛苦你自己学习一下 JavaScript，自己动手好了！加油。（有空我会看看的

**Comment by ClTheDove** [comment]
啊这，，好吧（

**Comment by ClTheDove** [comment]
把lang的值改了就行了，脚本里默认只改了tlang（翻译目标语言），但是不知道怎么获取字幕语言列表（也许可以参考其他关于字幕的脚本）和原视频语言（也许可以用google translate的自动检测语言）

**Comment by ClTheDove** [comment]
算了我先加个输入框吧（懒

**Comment by ookiineko** [comment]
语言列表似乎保存在 `ytInitialPlayerResponse.captions.playerCaptionsTracklistRenderer.captionTracks` 中
